apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: todoapp
type: Opaque
stringData:
  SECRET_KEY: "@e2(yx)v&tgh3_s=0yjm-j!hdpebxsz^dg47x)-k&kq_3zf*9e*"
  NAME: todoapp
  USER: todo_user
  PASSWORD: todo_password_change_me
  HOST: mysql-0.mysql.mysql.svc.cluster.local
